name: Expo CI • Test
on: [push]
jobs:
  test:
    name: Install & Test (Jest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Run tests (CI)
        run: npm run test:ci
